---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: rust:latest
  commands:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo install --path .
  - apt-get update && apt-get install -y ninja-build
  - make -C src/tests
---
kind: signature
hmac: 088ac7ba81932caf9a37bf05fee11a0f04efb5ccaaf93aea2bfe9fdc81983392

...
