name: Run tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    steps:
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.2
      with:
        version: "v0.4.0-pre.9"

    - name: rust cache
      uses: Swatinem/rust-cache@v2

    - uses: taiki-e/install-action@v2
      with:
        tool: grcov,cargo-binstall

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: "installing prerequisites"
      run: |
        sudo apt-get install -y ninja-build python3-requests
        rustup +nightly component add llvm-tools-preview
        cargo binstall -y --no-symlinks cargo-udeps
        git config --global init.defaultBranch main
        git config --global user.email "ci@riot-labs.de"
        git config --global user.name "CI"

    - name: "compiling with stable rust"
      run: cargo build
    - name: "stable unittests"
      run: cargo test --verbose --all

    - name: "stable end-to-end tests"
      run: "LAZE=$(pwd)/target/debug/laze make -C src/tests"

    - name: "compiling with nightly rust"
      run: "RUSTFLAGS=-Cinstrument-coverage cargo +nightly build"

    - name: "nightly unittests"
      run: "RUSTFLAGS=-Cinstrument-coverage cargo +nightly test"

    - name: "nightly end-to-end tests"
      run: "LAZE=$(pwd)/target/debug/laze make -C src/tests"

    - name: "checking for unused dependencies"
      run: cargo +nightly udeps

    - name: "collect coverage results"
      run: >
       RUSTUP_TOOLCHAIN=nightly
       grcov
       $(find . -name 'default*profraw' -print)
       --binary-path ./target/debug/laze
       --branch
       --output-path ./lcov.info
       --output-type lcov
       --source-dir .
       --ignore "/*"

    - name: Coveralls
      uses: coverallsapp/github-action@v1
      with:
        path-to-lcov: "lcov.info"
